# Generated by Django 5.1.1 on 2024-10-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_employeemodel_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
    ]
