# Generated by Django 5.1.1 on 2024-10-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_employeemodel_bio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeemodel',
            managers=[
            ],
        ),
    ]
