# Generated by Django 5.1.1 on 2024-10-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_employeemodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
    ]
