# Generated by Django 5.1.1 on 2024-10-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusermodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
    ]
