# Generated by Django 5.1.1 on 2024-10-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customusermodel_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='photo',
            field=models.ImageField(default='user_default_photo.png', upload_to='users/'),
        ),
    ]
