# Generated by Django 5.1.1 on 2024-10-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customusermodel_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
            ],
        ),
    ]
