# Generated by Django 5.1.1 on 2024-10-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customusermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='photo',
            field=models.ImageField(default='users/user_default_photo.png', upload_to='users/'),
        ),
    ]
