# Generated by Django 5.1.1 on 2024-10-09 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
    ]
