# Generated by Django 5.1.1 on 2024-10-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_commentsmodel_created_at_commentsmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Comment text'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Comment text'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Comment text'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
