# Generated by Django 5.1.1 on 2024-10-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_commentsmodel_text_en_commentsmodel_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('q_title', models.CharField(max_length=255, verbose_name='Question title')),
                ('question', models.TextField(verbose_name='Question text')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='offermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
