# Generated by Django 5.1.1 on 2024-10-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_questionmodel_offermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='likes_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='reply_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='views_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='likes_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='reply_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='views_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
