# Generated by Django 5.1.1 on 2024-10-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_offermodel_likes_count_offermodel_reply_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='q_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='q_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='q_title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='question_uz',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
    ]
