# Generated by Django 5.1.1 on 2024-10-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_questionmodel_answer_en_questionmodel_answer_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='q_title',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='q_title_en',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='q_title_ru',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='q_title_uz',
        ),
    ]
