# Generated by Django 5.1.1 on 2024-10-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_remove_questionmodel_q_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='commentsmodel',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='commentsmodel',
            name='text_uz',
        ),
    ]
